---
- name: NGINX | Install epel-release
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
  tags: nginx
- name: NGINX | Install NGINX
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
  notify: start-nginx
  ignore_errors: "{{ ansible_check_mode }}"
  tags: nginx
- name: NGINX | Create file for lighthouse config
  become: true
  ansible.builtin.file:
    path: /etc/nginx/conf.d/lighthouse.conf
    state: touch
    mode: 0644
  tags: nginx
- name: NGINX | Create general config
  become: true
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
  notify: reload-nginx
  tags: nginx
- name: Lighthouse | Install dependencies
  become: true
  ansible.builtin.yum:
    name: git
    state: present
  tags: lighthouse
- name: Lighthouse | Copy from git
  become: true
  git:
    repo: "{{ lighthouse_vcs }}"
    version: master
    dest: "{{ lighthouse_location_dir }}"
  ignore_errors: "{{ ansible_check_mode }}"
  tags: lighthouse
- name: Lighthouse | Create lighthouse config
  become: true
  template:
    src: lighthouse.conf.j2
    dest: /etc/nginx/conf.d/lighthouse.conf
    mode: 0644
  notify: reload-nginx
  tags: lighthouse
